/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Infer: typeof import('./src/components/helps/infer.vue')['default']
    Load_models: typeof import('./src/components/helps/load_models.vue')['default']
    Model_card: typeof import('./src/components/infer/model_card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Safety: typeof import('./src/components/helps/safety.vue')['default']
    Select_model: typeof import('./src/components/infer/select_model.vue')['default']
    Status_card: typeof import('./src/components/infer/status_card.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCel: typeof import('vant/es')['Cel']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanContactCard: typeof import('vant/es')['ContactCard']
    VanContactList: typeof import('vant/es')['ContactList']
    VanField: typeof import('vant/es')['Field']
    VanH4: typeof import('vant/es')['H4']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerColumn: typeof import('vant/es')['PickerColumn']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSelect: typeof import('vant/es')['Select']
    VanSelectOption: typeof import('vant/es')['SelectOption']
    VanSpace: typeof import('vant/es')['Space']
    VanSpan: typeof import('vant/es')['Span']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTag: typeof import('vant/es')['Tag']
    VanTextarea: typeof import('vant/es')['Textarea']
    VanToolbar: typeof import('vant/es')['Toolbar']
    VanToolbarButton: typeof import('vant/es')['ToolbarButton']
    VanToolbarTitle: typeof import('vant/es')['ToolbarTitle']
    VantTextarea: typeof import('vant/es')['tTextarea']
  }
}
